--------------------------------------------------------
--  파일이 생성됨 - 수요일-1월-13-2016   
--------------------------------------------------------
REM INSERTING into JUNGLECAST.ARTICLE
SET DEFINE OFF;
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (181,1,'5일 만에 백만 개가 팔린 일본의 쩌는 롤케이크','쥬륵......',9,0,0,1,381,23,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (184,1,'맨날 먹으면서도 몰랐던 순대의 비밀','물론 이런 거 몰라도
맛있으면 장땡',10,1,0,0,396,23,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (183,1,'가습기를 대신할 만한 습도를 높이는 가습 식물','가습기 무서워.',15,6,0,1,391,24,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (185,1,'고양이도 눈이 있다구요 외모로 사람 가리는 냥이','JTBC ''마리와 나''
동물은 거짓말을 못한다더니...☆',6,0,0,0,401,27,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (186,1,' 루이비통의 새로운 모델이 된 배두나','Louis Vuitton SERIES 4
',9,1,0,4,405,22,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (187,0,'훅 불면 날아갈 것 같은 아슬아슬한 소인국 마을','걸리버가 된 것만 같아...!',11,0,0,8,407,21,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (188,41,'가장 성공한 너드 마크 저커버그의 한 마디',null,1,0,0,0,410,25,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (189,41,'흔들리되, 부러지지 말자. 쓰러지되, 무너지지 말자',null,0,0,0,0,417,30,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (190,41,'차 한 잔만 잘 마셔도  병원 갈 필요 없다는데','내 증상에 따라 골라 마시는, 겨울철 따뜻한 차 한 잔.
',0,0,0,0,424,25,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (191,41,'분위기를 깨지 않으려고 내 불만을 말하지 못했다','당신의 마음을 대신 읽어드립니다',0,0,0,0,426,26,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (192,41,'3인의 남자 쇼퍼홀릭이 알려주는 득템 노하우','3인의 고수에게 듣는, 쇼핑에서 득템하는 방법! 
',1,0,0,0,429,28,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (198,2,'두꺼운 삼겹살 vs 얇은 삼겹살','삼겹살 is 뭔들..♥
',0,0,0,0,467,23,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (194,41,'요즘 핫하다는 그 립스틱','22세기에서 온 립스틱..?
',2,0,0,0,444,29,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (195,41,'오사카에서만 판다는 거대한 소고기 덮밥','크코 빛난다 (츄릅)
',1,0,0,0,449,21,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (196,41,'헐리웃 스타 윌스미스의 아들이 치마를 입은 이유','윌 스미스의 아들 제이든 스미스,<br>
그가 치마를 입고 나선 이유는?!',5,0,0,0,451,22,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (197,2,' 당신이 알고 있는 셀럽들이 늙는다면?','셀럽들의 먼 훗날 모습.
',2,0,0,0,463,22,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (199,41,'누구나 한 번쯤은 들어본 적 있는 영시','로버트 프로스트의 ''가지 않은 길''',1,0,0,0,468,30,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (200,2,'우리 몸에 좋은 비타민이 풍부한 10대 음식','우리 몸은 우리가 지켜야죠♡
',1,1,0,1,478,24,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (201,2,'호그와트 연회장 뺨치는 하버드대 학생 식당','엄마. 저 대학 다시 갈래요.
',1,0,0,0,481,25,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (202,41,'50만 원 이하로 살 만한 저렴이 1월 노트북 추천','1월이다!!!!!! 노트북 사야 돼!!!!!!!!<br>
으아아아아아!!!!!!<br>
*가격은 다나와 최저가 2016.01.06 19:00 기준입니다.',3,0,0,0,487,24,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (203,41,'부산에 생기는 5성급 힐튼호텔의 위용','드디어 그분이 오셨다.',1,0,0,0,491,21,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (204,2,'노래로 만들어진 아홉 살 어린이의 사연','누군가의 사랑 이야기가 음악이 되기까지 #3
',3,0,0,0,498,26,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (205,2,'크기 전에는 강아지보다 귀엽다는 새끼 치타','치명적인 귀여움의 소유자
',6,1,2,1,507,27,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (206,41,' 그가 무심하게 건넨, 마음을 적신 선물 10','#. 여자가 받은 선물 ver.',11,1,2,0,511,26,to_date('16/01/11','RR/MM/DD'));
Insert into JUNGLECAST.ARTICLE (ARTICLE_ID,M_ID,ARTICLE_TITLE,ARTICLE_SUBTITLE,ARTICLE_VIEW,ARTICLE_LIKE,ARTICLE_SHARE,ARTICLE_REPLY,PIC_ID,CATEGORY_ID,ARTICLE_DATE) values (221,1,'인간의 노화 과정',null,1,0,0,0,521,21,to_date('16/01/13','RR/MM/DD'));
